FROM node:17-alpine3.12 AS api-tests-runner

RUN apk add --no-cache --virtual build-dependencies python2 g++ make

RUN apk add curl

RUN mkdir -p /var/www/api

ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

COPY . /var/www/api
COPY .env.test /var/www/api/.env.test

WORKDIR /var/www/api

RUN yarn
RUN yarn build