FROM mongo AS mongo-seed

COPY tests/seed/*.seed.json /

# drop existing test db and reimport seed for fresh test
CMD mongoimport --host db --db eosdac --collection actions --type json --file /actions.seed.json --jsonArray --drop && \
    mongoimport --host db --db eosdac --collection contract_rows --type json --file /contract_rows.seed.json --jsonArray --drop && \
    mongoimport --host db --db eosdac --collection state --type json --file /state.seed.json --jsonArray --drop && \
    mongoimport --host db --db eosdac --collection workerproposals --type json --file /workerproposals.seed.json --jsonArray --drop


FROM node:17-alpine3.12 AS api-tests-runner

RUN apk add --no-cache --virtual build-dependencies python2 g++ make

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

RUN apk add curl

RUN mkdir -p /var/www/api

COPY . /var/www/api
COPY .env-test /var/www/api/.env-${NODE_ENV}

WORKDIR /var/www/api

RUN yarn
RUN yarn build