module.exports = {
    getProposalsSchema: require('./get_proposals'),
    proposalsInboxSchema: require('./proposals_inbox'),
    proposalsCountsSchema: require('./proposals_counts'),
    getMsigProposalsSchema: require('./get_msig_proposals'),
    getProfileSchema: require('./get_profile'),
    balanceTimelineSchema: require('./balance_timeline'),
    memberSnapshotSchema: require('./member_snapshot'),
    votesTimelineSchema: require('./votes_timeline'),
    dacConfigSchema: require('./dac_config'),
    candidatesSchema: require('./candidates'),
    memberSchema: require('./member'),
    memberCountsSchema: require('./member_counts'),
    tokensOwnedSchema: require('./tokens_owned'),
    transfersSchema: require('./transfers'),
    votersSchema: require('./voters'),
    myDacsSchema: require('./my_dacs'),
    referendumsSchema: require('./referendums'),
};
